spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db-patrimoine}:5432/${DB_NAME:patrimoine_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}