spring:
  datasource:
    # Utilise le nom du conteneur 'pgvpt-postgres' défini dans le docker-compose
    url: jdbc:postgresql://pgvpt-postgres:5432/patrimoine_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
