server:
  port: 8761

spring:
  application:
    name: pgvpt-discovery

eureka:
  instance:
    hostname: pgvpt-discovery

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://pgvpt-discovery:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always